package service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.18
 * 2019-03-26T17:04:43.899+08:00
 * Generated source version: 3.1.18
 * 
 */
@WebService(targetNamespace = "http://service.queryapi.person.creditquery.dhcc.com.cn/", name = "CpqPersonReportQueryServiceWS")
@XmlSeeAlso({ObjectFactory.class})
public interface CpqPersonReportQueryServiceWS {

    @WebMethod
    @RequestWrapper(localName = "getSyncCreditReport", targetNamespace = "http://service.queryapi.person.creditquery.dhcc.com.cn/", className = "cn.com.dhcc.creditquery.person.queryapi.service.GetSyncCreditReport")
    @ResponseWrapper(localName = "getSyncCreditReportResponse", targetNamespace = "http://service.queryapi.person.creditquery.dhcc.com.cn/", className = "cn.com.dhcc.creditquery.person.queryapi.service.GetSyncCreditReportResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getSyncCreditReport(
        @WebParam(name = "reqid", targetNamespace = "")
        java.lang.String reqid
    );

    @WebMethod
    @RequestWrapper(localName = "getCreditReport", targetNamespace = "http://service.queryapi.person.creditquery.dhcc.com.cn/", className = "cn.com.dhcc.creditquery.person.queryapi.service.GetCreditReport")
    @ResponseWrapper(localName = "getCreditReportResponse", targetNamespace = "http://service.queryapi.person.creditquery.dhcc.com.cn/", className = "cn.com.dhcc.creditquery.person.queryapi.service.GetCreditReportResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getCreditReport(
        @WebParam(name = "parXml", targetNamespace = "")
        java.lang.String parXml
    );
}
