package service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.18
 * 2019-03-26T17:04:43.927+08:00
 * Generated source version: 3.1.18
 * 
 */
@WebServiceClient(name = "CpqPersonReportQueryServiceWSService", 
                  wsdlLocation = "http://localhost:19090/personqueryapiweb/webservice/ReportQuery?wsdl",
                  targetNamespace = "http://service.queryapi.person.creditquery.dhcc.com.cn/") 
public class CpqPersonReportQueryServiceWSService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.queryapi.person.creditquery.dhcc.com.cn/", "CpqPersonReportQueryServiceWSService");
    public final static QName CpqPersonReportQueryServiceWSPort = new QName("http://service.queryapi.person.creditquery.dhcc.com.cn/", "CpqPersonReportQueryServiceWSPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:19090/personqueryapiweb/webservice/ReportQuery?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CpqPersonReportQueryServiceWSService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:19090/personqueryapiweb/webservice/ReportQuery?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CpqPersonReportQueryServiceWSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CpqPersonReportQueryServiceWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CpqPersonReportQueryServiceWSService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public CpqPersonReportQueryServiceWSService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CpqPersonReportQueryServiceWSService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CpqPersonReportQueryServiceWSService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns CpqPersonReportQueryServiceWS
     */
    @WebEndpoint(name = "CpqPersonReportQueryServiceWSPort")
    public CpqPersonReportQueryServiceWS getCpqPersonReportQueryServiceWSPort() {
        return super.getPort(CpqPersonReportQueryServiceWSPort, CpqPersonReportQueryServiceWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CpqPersonReportQueryServiceWS
     */
    @WebEndpoint(name = "CpqPersonReportQueryServiceWSPort")
    public CpqPersonReportQueryServiceWS getCpqPersonReportQueryServiceWSPort(WebServiceFeature... features) {
        return super.getPort(CpqPersonReportQueryServiceWSPort, CpqPersonReportQueryServiceWS.class, features);
    }

}
